
font:
  size: 9
  normal:
    family: Liberation Mono
    style: Regular

  bold:
    family: Liberation Mono
    style: Bold

  italic:
    family: Liberation Mono
    style: Italic

  bold_italic:
    family: Liberation Mono
    style: Bold Italic

# Force Shift-Backspace to behave just like Backspace
# https://github.com/alacritty/alacritty/issues/3652
key_bindings:
     - { key: Back, mods: Shift, chars: "\x7f" }

