#theme = "Base16-Default-Dark"

window.opacity=0.95

[colors.bright]
black = "#585858"
blue = "#7cafc2"
cyan = "#86c1b9"
green = "#a1b56c"
magenta = "#ba8baf"
red = "#ab4642"
white = "#f8f8f8"
yellow = "#f7ca88"

[colors.cursor]
cursor = "#d8d8d8"
text = "#d8d8d8"

[colors.normal]
black = "#181818"
blue = "#7cafc2"
cyan = "#86c1b9"
green = "#a1b56c"
magenta = "#ba8baf"
red = "#ab4642"
white = "#d8d8d8"
yellow = "#f7ca88"

[colors.primary]
background = "#181818"
foreground = "#d8d8d8"

[font]
size = 9

[font.bold]
family = "Liberation Mono"
style = "Bold"

[font.bold_italic]
family = "Liberation Mono"
style = "Bold Italic"

[font.italic]
family = "Liberation Mono"
style = "Italic"

[font.normal]
family = "Liberation Mono"
style = "Regular"
