#!/usr/bin/env bash

# Like `tmux select-pane`, but if Vim is running in the current pane it sends a
# keystroke to Vim instead to let it decide whether it's going to switch windows
# internally or switch tmux panes.
#
# https://gist.github.com/mislav/5189704

set -e

cmd="$(tmux display -p '#{pane_current_command}')"
cmd="$(basename "$cmd" | tr A-Z a-z)"

if [[ "${cmd%m}" == "vi" || "${cmd%m}" == "nvi" ]]; then
  direction="$(echo "${1#-}" | sed -e 's/D/j/' -e 's/U/k/' -e 's/L/h/' -e 's/R/l/')"
  # forward the keystroke to Vim
  tmux send-keys "M-$direction"
else
  tmux select-pane "$@"
  #echo "2-- $@" >>/tmp/xxx.log
fi
