icons_format = "{icon}"

[theme]
theme = "srcery"
#theme = "gruvbox-dark"
#theme = "slick"

[icons]
icons = "material-nf"
#icons = "awesome6"

[[block]]
block = "focused_window"

[[block]]
block = "nvidia_gpu"

#[[block]]
#block = "memory"
#format = " $icon $mem_total_used_percents.eng(w:2) "
#format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"

[[block]]
block = "disk_space"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid|Wired connection}"

[[block]]
block = "speedtest"
format = " ^icon_net_down $speed_down ^icon_net_up $speed_up "

[[block]]
block = "battery"

[[block]]
block = "keyboard_layout"
driver = "sway"
[block.mappings]
"English (US)" = "EN-US"
"English (US, intl., with dead keys)" = "EN-INTL"
"Portuguese (Brazil)" = "BR"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
