icons = "awesome5"

[theme]
name = "modern"

[theme.overrides]
separator = ""           # No sep
idle_bg = "#222222"      # black?
good_bg = "#99c794"      # green
info_bg = "#6699cc"      # blue
critical_bg = "#ec5f67"  # red
warning_bg = "#fac863"   # yellow

[[block]]
block = "focused_window"
max_width = 60

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
icons = true
clickable = true
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 10
format = "{barchart} {utilization}"

[[block]]
block = "net"
device = "wlp2s0"
interval = 5

#[[block]]
#block = "battery"
#interval = 10
#format = "{percentage}% {time}"

[[block]]
block = "custom"
command = "xkb-layout"
json = true
interval = 1

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
