icons = "awesome"

[theme]
name = "modern"

[theme.overrides]
separator = ""           # No sep
idle_bg = "#222222"      # black?
good_bg = "#99c794"      # green
info_bg = "#6699cc"      # blue
critical_bg = "#ec5f67"  # red
warning_bg = "#fac863"   # yellow

[[block]]
block = "focused_window"
max_width = 60

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 3
format = "{barchart} {utilization}%"

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
ip = false
speed_up = false
speed_down = false
graph_up = false
interval = 5

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "custom"
command = "xkb-layout"
json = true
interval = 1

